apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: test-spring-container
        image: isshomin/test-spring:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8999
